export enum ProgLangs {
  JavaScript = 'JavaScript',
  TypeScript = 'TypeScript',
  Python = 'Python',
  Go = 'Go',
  C = 'C',
  Ruby = 'Ruby',
  Java = 'Java',
  CPP = 'C++',
  Lua = 'Lua',
  Lisp = 'Lisp',
  Elixir = 'Elixir',
  Pascal = 'Pascal',
  Haskell = 'Haskell',
  Ada = 'Ada',
  Assembler = 'Assembler',
  Rust = 'Rust',
}
